name: CI - Pruebas Automatizadas

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y ejecutar pruebas
        run: mvn clean test

      - name: Guardar reporte de pruebas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas
          path: target/surefire-reports/